import { useEffect, useState } from "react";
import { BrowserRouter, Routes, Route, Link, Navigate, useParams, useNavigate } from "react-router-dom";
import "./App.css";
import { apiRequest } from "./apiClient";

const fields = [
  ["currentVolume", "Current annual volume"], ["projectedVolume", "Projected annual volume"],
  ["annualCapacity", "Annual capacity"], ["netRevenuePerCase", "Net revenue per case ($)"],
  ["variableCostPerCase", "Variable cost per case ($)"],
  ["additionalAnnualFixedCost", "Additional annual fixed cost ($)"], ["initialInvestment", "Initial investment ($)"]
];
const emptyInputs = () => Object.fromEntries(fields.map(([key]) => [key, ""]));
const editable = item => ["Draft", "Returned", "Open", "In Progress"].includes(item.status);
function ErrorMessage({ message }) { return message ? <p className="error-message" role="alert">{message}</p> : null; }
function Login() {
  return <div className="page"><div className="card"><h2>Welcome to StratSight</h2>
    <p>Healthcare Strategic Decision Support</p><p>Assess service line opportunities and submit them for leadership review.</p>
    <a className="primary-button link-button" href="http://localhost:3000/login">Login with Amazon Cognito</a></div></div>;
}
function AssessmentMetrics({ metrics }) {
  if (!metrics) return <p>Complete the assessment inputs to calculate metrics.</p>;
  const format = (value, suffix = "", money = false) => value == null ? "Not applicable" :
    new Intl.NumberFormat("en-US", { maximumFractionDigits: 2, ...(money ? { style: "currency", currency: "USD" } : {}) }).format(value) + suffix;
  const rows = [
    ["Incremental annual volume", format(metrics.incrementalVolume)],
    ["Volume growth", format(metrics.volumeGrowthPercent, "%")],
    ["Projected capacity utilization", format(metrics.projectedCapacityUtilizationPercent, "%")],
    ["Volume exceeding capacity", format(metrics.capacityGap)],
    ["Contribution per case", format(metrics.contributionPerCase, "", true)],
    ["Incremental annual contribution", format(metrics.incrementalAnnualContribution, "", true)],
    ["Simple payback", format(metrics.simplePaybackYears, " years")]
  ];
  return <section><h3>Strategic Decision Dashboard</h3><table><thead><tr><th scope="col">Metric</th><th scope="col">Result</th></tr></thead>
    <tbody>{rows.map(([label, value]) => <tr key={label}><th scope="row">{label}</th><td>{value}</td></tr>)}</tbody></table>
    <p>Simple payback excludes discounting and assumes a constant annual contribution.</p></section>;
}
function Initiatives({ user }) {
  const [items, setItems] = useState([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  useEffect(() => { let active = true;
    apiRequest("/api/insights").then(r => { if (active) setItems(r.data || []); })
      .catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, []);
  return <div className="page"><div className="page-header"><div><h2>{user.role === "Analyst" ? "My Assessments" : "Leadership Review"}</h2>
    <p>{user.role === "Analyst" ? "Create and manage strategic assessments." : "Review submitted assessments and track decisions."}</p></div>
    {user.role === "Analyst" && <Link className="primary-button link-button" to="/initiatives/new">New Assessment</Link>}</div>
    <ErrorMessage message={error}/><div className="card">{loading ? <p>Loading assessments...</p> : items.length === 0 ? <p>No assessments available yet.</p> :
      items.map(item => <div className="initiative-item" key={item.insightId}><div><h3>{item.title}</h3><p>{item.category} · <strong>{item.status}</strong></p></div>
        <Link to={`/initiatives/${item.insightId}`}>View Details</Link></div>)}</div></div>;
}
function ExecutiveInterpretation({
  item,
  canGenerate,
  onGenerated,
}) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");

  async function generate() {
    setBusy(true);
    setError("");

    try {
      const result = await apiRequest(
        `/api/insights/${item.insightId}/interpretation`,
        { method: "POST" }
      );

      onGenerated(result.data);
    } catch (error) {
      setError(error.message);
    } finally {
      setBusy(false);
    }
  }

  return (
    <section>
      <h3>Executive Interpretation</h3>

      <ErrorMessage message={error} />

      {item.executiveInterpretation?.text ? (
        <>
          <p style={{ whiteSpace: "pre-wrap" }}>
            {item.executiveInterpretation.text}
          </p>

          <p>
            Generated by{" "}
            {item.executiveInterpretation.source || "AI"}
            {" · "}
            {new Date(
              item.executiveInterpretation.generatedAt
            ).toLocaleString()}
          </p>
        </>
      ) : (
        <p>No executive interpretation generated yet.</p>
      )}

      {canGenerate && (
        <button
          type="button"
          disabled={busy || !item.assessmentInputs}
          onClick={generate}
        >
          {busy
            ? "Generating..."
            : "Generate DRIFT Interpretation"}
        </button>
      )}

      <p>
        AI-generated interpretation requires leadership validation.
      </p>
    </section>
  );
}
function InitiativeDetail({ user }) {
  const { id } = useParams(), navigate = useNavigate();
  const [item, setItem] = useState(null), [error, setError] = useState(""), [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false), [comment, setComment] = useState("");
  useEffect(() => { let active = true;
    setLoading(true); setError("");
    apiRequest(`/api/insights/${id}`).then(r => { if (active) setItem(r.data); })
      .catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [id]);
  async function act(action, decision) {
    setBusy(true); setError("");
    try {
      const result = await apiRequest(`/api/insights/${id}${action === "delete" ? "" : `/${action}`}`, {
        method: action === "delete" ? "DELETE" : "POST",
        ...(action === "review" ? { body: JSON.stringify({ decision, comment }) } : {})
      });
      if (action === "delete") navigate("/initiatives");
      else { setItem(result.data); setComment(""); }
    } catch (e) { setError(e.message); } finally { setBusy(false); }
  }
  if (loading) return <div className="page"><p>Loading assessment...</p></div>;
  if (!item) return <div className="page"><ErrorMessage message={error}/><Link to="/initiatives">Back to Assessments</Link></div>;
  const owner = user.role === "Analyst" && item.ownerId === user.userId;
  const reviewer = ["Director", "Executive"].includes(user.role) && item.ownerId !== user.userId && item.status === "Submitted";
  return <div className="page"><div className="card"><h2>{item.title}</h2><ErrorMessage message={error}/>
    <p>{item.description}</p><p><strong>Category:</strong> {item.category}</p><p><strong>Status:</strong> {item.status}</p>
    <AssessmentMetrics metrics={item.metrics}/>
    <ExecutiveInterpretation
      item={item}
      canGenerate={owner && editable(item)}
      onGenerated={setItem}
    />

    <details><summary>Assessment inputs</summary>{fields.map(([key, label]) => <p key={key}><strong>{label}:</strong> {item.assessmentInputs?.[key] ?? "Not entered"}</p>)}</details>
    {owner && editable(item) && <div className="form-actions"><Link className="primary-button link-button" to={`/initiatives/${id}/edit`}>Edit Assessment</Link>
      <button disabled={busy || !item.assessmentInputs} onClick={() => act("submit")}>Submit for Review</button>
      <button disabled={busy} onClick={() => { if (window.confirm("Delete this assessment permanently?")) act("delete"); }}>Delete Assessment</button></div>}
    {owner && !editable(item) && <p>This assessment is locked while submitted or approved.</p>}
    {reviewer && <form onSubmit={e => { e.preventDefault(); act("review", "Approved"); }}><h3>Leadership Review</h3>
      <div className="form-group"><label htmlFor="review-comment">Review comment</label><textarea id="review-comment" required maxLength={4000} rows={4}
        value={comment} onChange={e => setComment(e.target.value)}/></div><div className="form-actions">
      <button className="primary-button" disabled={busy || !comment.trim()} type="submit">Approve</button>
      <button disabled={busy || !comment.trim()} type="button" onClick={() => act("review", "Returned")}>Return for Changes</button></div></form>}
    <h3>Status History and Comments</h3>{item.history?.length ? <ol>{item.history.map((entry, index) => <li key={index}>
      <strong>{entry.action} — {entry.status}</strong><p>{entry.actorEmail || entry.actorId} ({entry.actorRole}) · {new Date(entry.at).toLocaleString()}</p>
      {entry.comment && <p>{entry.comment}</p>}</li>)}</ol> : <p>No history recorded for this older assessment.</p>}
    <p>Last updated: {new Date(item.updatedAt).toLocaleString()}</p><Link to="/initiatives">Back to Assessments</Link></div></div>;
}
function AssessmentForm({ user }) {
  const { id } = useParams(), navigate = useNavigate();
  const [values, setValues] = useState({ title: "", description: "", category: "" });
  const [inputs, setInputs] = useState(emptyInputs), [status, setStatus] = useState("Draft");
  const [loading, setLoading] = useState(Boolean(id)), [saving, setSaving] = useState(false), [error, setError] = useState("");
  const [allowed, setAllowed] = useState(true);
  useEffect(() => { if (!id) return; let active = true;
    apiRequest(`/api/insights/${id}`).then(({ data }) => { if (!active) return;
      setAllowed(editable(data) && data.ownerId === user.userId); setStatus(data.status);
      setValues({ title: data.title, description: data.description, category: data.category });
      setInputs({ ...emptyInputs(), ...(data.assessmentInputs || {}) });
    }).catch(e => { if (active) { setError(e.message); setAllowed(false); } }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, [id, user.userId]);
  async function save(e) {
    e.preventDefault(); setError("");
    if (fields.some(([key]) => inputs[key] === "" || !Number.isFinite(Number(inputs[key])))) { setError("Complete all seven numeric inputs."); return; }
    setSaving(true);
    try { const result = await apiRequest(id ? `/api/insights/${id}` : "/api/insights", {
      method: id ? "PUT" : "POST", body: JSON.stringify({ ...values, status,
        assessmentInputs: Object.fromEntries(fields.map(([key]) => [key, Number(inputs[key])])) })
    }); navigate(`/initiatives/${result.data.insightId}`); }
    catch (e) { setError(e.message); } finally { setSaving(false); }
  }
  if (user.role !== "Analyst") return <div className="page"><p>Only analysts can create or edit assessments.</p><Link to="/initiatives">Back</Link></div>;
  if (loading) return <div className="page"><p>Loading assessment...</p></div>;
  return <div className="page"><div className="card"><h2>{id ? "Edit Assessment" : "Create Assessment"}</h2><ErrorMessage message={error}/>
    {!allowed ? <p>This assessment cannot be edited.</p> : <form onSubmit={save}>
      {[["title", "Title"], ["description", "Description"], ["category", "Service line / category"]].map(([key, label]) => <div className="form-group" key={key}>
        <label htmlFor={key}>{label}</label>{key === "description" ? <textarea id={key} required rows={4} value={values[key]} onChange={e => setValues({ ...values, [key]: e.target.value })}/> :
          <input id={key} required value={values[key]} onChange={e => setValues({ ...values, [key]: e.target.value })}/>}</div>)}
      <fieldset><legend>Strategic assessment inputs</legend><p>Use sample data. Volume figures cover one year.</p>
        {fields.map(([key, label]) => <div className="form-group" key={key}><label htmlFor={key}>{label}</label>
          <input id={key} type="number" required min={key === "annualCapacity" ? 1 : 0}
            step={key.includes("Volume") || key === "annualCapacity" ? 1 : 0.01} value={inputs[key]}
            onChange={e => setInputs({ ...inputs, [key]: e.target.value })}/></div>)}</fieldset>
      <p>Status: {status}</p><button className="primary-button" disabled={saving}>{saving ? "Saving..." : "Save Assessment"}</button></form>}
    <p><Link to={id ? `/initiatives/${id}` : "/initiatives"}>Cancel</Link></p></div></div>;
}
function AppLayout() {
  const [user, setUser] = useState(null), [loading, setLoading] = useState(true), [error, setError] = useState("");
  useEffect(() => { let active = true;
    fetch("http://localhost:3000/api/me", { credentials: "include", cache: "no-store" }).then(async r => {
      if (r.status === 401) return;
      const data = await r.json(); if (!r.ok) throw new Error(data.message || "Unable to verify account");
      if (active) setUser(data.user);
    }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); });
    return () => { active = false; };
  }, []);
  const protect = element => loading ? <p>Checking authentication...</p> : error ? <ErrorMessage message={error}/> : user ? element : <Navigate to="/login" replace/>;
  return <div className="app"><header className="navbar"><div><h1>StratSight</h1><p>Healthcare Strategic Decision Support</p></div><nav>
    <Link to="/initiatives">Assessments</Link>{user && <><span>{user.email} · {user.role}</span><a href="http://localhost:3000/logout">Logout</a></>}</nav></header>
    <main><Routes><Route path="/" element={<Navigate to="/initiatives" replace/>}/><Route path="/login" element={<Login/>}/>
      <Route path="/initiatives" element={protect(<Initiatives user={user}/>)}/>
      <Route path="/initiatives/new" element={protect(<AssessmentForm key="new" user={user}/>)}/>
      <Route path="/initiatives/:id" element={protect(<InitiativeDetail user={user}/>)}/>
      <Route path="/initiatives/:id/edit" element={protect(<AssessmentForm key="edit" user={user}/>)}/>
      <Route path="*" element={<Navigate to="/initiatives" replace/>}/></Routes></main></div>;
}
export default function App() { return <BrowserRouter><AppLayout/></BrowserRouter>; }